# Generated by Django 2.2.7 on 2019-11-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starting5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nba_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='player',
            name='nbateam',
            field=models.CharField(default='NBA Team', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='starting5.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='My Team Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Player Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='summary',
            field=models.CharField(default='How I Describe My Team', max_length=100),
        ),
    ]
