# Generated by Django 2.2.7 on 2019-11-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting5', '0002_auto_20191107_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nbateam',
            new_name='nba_team',
        ),
    ]
